-- Create user
INSERT INTO TW_USER (ID, VERSION, TRUSTED, DATE_CREATED, FIRST_NAME, NOTIFICATION, LAST_UPDATED, LAST_ACCESS, ORGANIZATION, USER_NAME, DISABLED, OPTIONS, AUTH_TIME, LAST_NAME, DESCRIPTION, EMAIL, AUTH_TOKEN, AVATAR)
VALUES (1, 0, TRUE, CURRENT_TIMESTAMP, null, null, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, null, 'tower-user', null, null, CURRENT_TIMESTAMP, null, null, 'example.com', '<<AUTH_TOKEN>>', null);
-- Create user role
INSERT INTO TW_ROLE (ID, VERSION, AUTHORITY)
VALUES (1, 0, 'ROLE_USER');
-- Add user to the role
INSERT INTO TW_USER_ROLE (ID, VERSION, ROLE_ID, USER_ID)
VALUES (1, 0, 1, 1);
-- Create access token and add it to the user
INSERT INTO TW_ACCESS_TOKEN (ID, VERSION, DATE_CREATED, NAME, USER_ID, TOKEN, LAST_USED)
VALUES (1, 0, CURRENT_TIMESTAMP, 'default', 1, '<<ACCESS_TOKEN>>', null);